### ISSUE TITLE
GitHub Actions: Auto assign closed issues to project board

### ISSUE THREAD

**Issue by Shrinks99** [webrecorder/.github#1]
From today's call: Would be nice to automatically do this via a GItHub action starting with the Browsertrix Cloud repo.

The action should always move closed issues to the current sprint.

**Comment by DaleLore** [comment]
Testing to see where the issue goes to when Closed

**Comment by DaleLore** [comment]
Clarification to issue: Auto-assign ANY closed issue to current sprint

**Comment by Shrinks99** [comment]
Also maybe 'completed' issues if possible, I don't think 'closed as not planned' should be added?
