### ISSUE TITLE
GitHub Actions Auto Assign Normal Priority

### ISSUE THREAD

**Issue by tw4l** [webrecorder/.github#2]
In order to ensure the Priority field is being used properly so things sort nicely within the task board we need to auto assign the priority label to every item that is added to the task board.

Additionally we would like to auto assign every issue from the Browsertrix Cloud repo to the board.

**Comment by tw4l** [comment]
Creating issue within browsertrix-cloud to make it easier to track, though this applies to several repos

**Comment by SuaYoo** [comment]
Auto-assign now set up using https://github.com/actions/add-to-project, default status of "Triage" is set in the [Workflow settings](https://github.com/orgs/webrecorder/projects/9/workflows/2688868)

**Comment by SuaYoo** [comment]
I tried setting up [update-project-action](https://github.com/github/update-project-action) in [project-assign-issue.yml](https://github.com/webrecorder/browsertrix-cloud/blob/main/.github/workflows/project-assign-issue.yml) for field updates but couldn't get past "Item not found with ID". Not sure if it's a documentation issue or misconfiguration on my part, but I opened https://github.com/github/update-project-action/issues/55.

**Comment by SuaYoo** [comment]
It looks like this is possible with https://github.com/leonsteinhaeuser/project-beta-automations#json-definition, which is already implemented in `project-assign-issue.yml`. Maybe that workflow can be generalized into `project-automation.yml`? The repo for `leonsteinhaeuser/project-beta-automation` has good examples.

**Comment by ikreymer** [comment]
Might not need this anymore, closing for now. Just using low / urgent priority as needed.
